WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80dc953690>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/153edf670ef0b40e11c1d81d51e0fc9d/url
WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80dc953a50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/153edf670ef0b40e11c1d81d51e0fc9d/url
WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80dc953710>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/153edf670ef0b40e11c1d81d51e0fc9d/url
WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80dce3d590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/153edf670ef0b40e11c1d81d51e0fc9d/timeouts
WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80dce3d790>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/153edf670ef0b40e11c1d81d51e0fc9d/timeouts
WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80dce59ad0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/153edf670ef0b40e11c1d81d51e0fc9d/timeouts
WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80dce3df90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/153edf670ef0b40e11c1d81d51e0fc9d
WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80dce54dd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/153edf670ef0b40e11c1d81d51e0fc9d
WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80dc943290>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/153edf670ef0b40e11c1d81d51e0fc9d